# Generated by Django 5.2.5 on 2025-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrator'), ('admin', 'Administrator'), ('manager', 'Security Manager'), ('analyst', 'Security Analyst'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
