# Generated by Django 5.0.14 on 2025-08-18 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('technology', 'Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('government', 'Government'), ('other', 'Other')], default='technology', max_length=50)),
                ('employee_count', models.CharField(choices=[('1-50', '1-50'), ('51-200', '51-200'), ('200-500', '200-500'), ('500-1000', '500-1000'), ('1000+', '1000+')], default='1-50', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('founded_year', models.CharField(blank=True, max_length=4)),
                ('timezone', models.CharField(choices=[('UTC-12', 'UTC-12 (Baker Island)'), ('UTC-8', 'UTC-8 (Pacific)'), ('UTC-5', 'UTC-5 (Eastern)'), ('UTC+0', 'UTC+0 (London)'), ('UTC+1', 'UTC+1 (Berlin)'), ('UTC+8', 'UTC+8 (Singapore)'), ('UTC+9', 'UTC+9 (Tokyo)')], default='UTC+0', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh', 'Chinese'), ('ja', 'Japanese')], default='en', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
    ]
