# Generated by Django 5.2.5 on 2025-08-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_company_domain_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
