# Generated by Django 5.2.5 on 2025-08-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_company_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
