# Generated by Django 5.2.5 on 2025-08-17 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('credential', 'Credential Phishing'), ('data_input', 'Data Input Form'), ('link_click', 'Link Click Tracking'), ('attachment', 'Fake Attachment'), ('social_engineering', 'Social Engineering')], max_length=50)),
                ('description', models.TextField()),
                ('email_subject', models.CharField(max_length=200)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('html_content', models.TextField()),
                ('css_styles', models.TextField(blank=True)),
                ('landing_page_url', models.URLField(blank=True)),
                ('domain', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('low', 'Low'), ('intermediate', 'Intermediate'), ('high', 'High'), ('advanced', 'Advanced')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('intermediate', 'Intermediate'), ('high', 'High'), ('advanced', 'Advanced')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('has_attachments', models.BooleanField(default=False)),
                ('has_css', models.BooleanField(default=False)),
                ('is_responsive', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='template_thumbnails/')),
                ('usage_count', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('tracking_enabled', models.BooleanField(default=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='template_attachments/')),
                ('filename', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('is_malicious_simulation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='templates.template')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('templates', models.ManyToManyField(blank=True, related_name='tags', to='templates.template')),
            ],
        ),
    ]
