# Generated by Django 5.2.5 on 2025-08-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_company_options'),
        ('templates', '0002_alter_template_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organization.company'),
        ),
    ]
