# Generated by Django 5.2.5 on 2025-08-17 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField(default=0)),
                ('total_campaigns', models.IntegerField(default=0)),
                ('total_templates', models.IntegerField(default=0)),
                ('high_risk_employees', models.IntegerField(default=0)),
                ('medium_risk_employees', models.IntegerField(default=0)),
                ('low_risk_employees', models.IntegerField(default=0)),
                ('overall_click_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overall_submission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('training_completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('monthly_metrics', models.JSONField(blank=True, null=True)),
                ('industry_average_click_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('industry_average_submission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_targets', models.IntegerField(default=0)),
                ('emails_delivered', models.IntegerField(default=0)),
                ('emails_opened', models.IntegerField(default=0)),
                ('links_clicked', models.IntegerField(default=0)),
                ('forms_submitted', models.IntegerField(default=0)),
                ('attachments_downloaded', models.IntegerField(default=0)),
                ('delivery_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('open_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('click_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('submission_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('download_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('average_time_to_click', models.DurationField(blank=True, null=True)),
                ('average_time_to_submit', models.DurationField(blank=True, null=True)),
                ('peak_activity_hour', models.IntegerField(blank=True, null=True)),
                ('department_stats', models.JSONField(blank=True, null=True)),
                ('timeline_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_report', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('campaign_stats', 'Campaign Statistics'), ('employee_risk', 'Employee Risk Distribution'), ('recent_activity', 'Recent Activity'), ('success_rates', 'Success Rates'), ('department_performance', 'Department Performance'), ('trend_chart', 'Trend Chart')], max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=1)),
                ('configuration', models.JSONField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('campaign_summary', 'Campaign Summary'), ('employee_performance', 'Employee Performance'), ('department_analysis', 'Department Analysis'), ('security_metrics', 'Security Metrics'), ('trend_analysis', 'Trend Analysis'), ('custom', 'Custom Report')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('data', models.JSONField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='reports', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='reports', to='employees.department')),
                ('employees', models.ManyToManyField(blank=True, related_name='reports', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
