# Generated by Django 5.2.5 on 2025-08-22 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_accounts', '0001_initial'),
    ]

    operations = [
    ]
