# Generated by Django 5.2.5 on 2025-08-22 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_emaildomain_domainverificationtoken_emailtemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='campaigns.emaildomain'),
        ),
    ]
