# Generated by Django 5.2.5 on 2025-08-20 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_department_created_by_employee_created_by_and_more'),
        ('organization', '0004_alter_company_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='organization.company'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_employees', to='organization.company'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('email', 'organization'), ('employee_id', 'organization')},
        ),
    ]
